/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.awt.Color;
import static java.lang.String.valueOf;
import javax.swing.JFrame;

/**
 *
 * @author imamah
 */
public class HomePage extends javax.swing.JFrame {
    String loggedIn;
    /**
     * Creates new form HomePage
     */
    public HomePage(String email) {
        this.loggedIn=email;
        System.out.println(loggedIn);
             setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
        initComponents();
           //displayCountOfItems.setText(valueOf(count));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PretBuyButton = new javax.swing.JLabel();
        unStichedBuyButton = new javax.swing.JLabel();
        unStichedBuyButton1 = new javax.swing.JLabel();
        unStichedBuyButton2 = new javax.swing.JLabel();
        unStichedBuyButton3 = new javax.swing.JLabel();
        unStichedBuyButton4 = new javax.swing.JLabel();
        unStichedBuyButton5 = new javax.swing.JLabel();
        unStichedBuyButton6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        LogOut2 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 233, 225));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 610));

        jPanel2.setBackground(new java.awt.Color(36, 47, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 206, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 62, -1));

        PretBuyButton.setBackground(new java.awt.Color(176, 233, 225));
        PretBuyButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PretBuyButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PretBuyButton.setText("Heavy vehicles");
        PretBuyButton.setOpaque(true);
        PretBuyButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PretBuyButtonMouseMoved(evt);
            }
        });
        PretBuyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PretBuyButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PretBuyButtonMouseExited(evt);
            }
        });
        jPanel2.add(PretBuyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 140, 31));

        unStichedBuyButton.setBackground(new java.awt.Color(176, 233, 225));
        unStichedBuyButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unStichedBuyButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unStichedBuyButton.setText("Customers");
        unStichedBuyButton.setOpaque(true);
        unStichedBuyButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unStichedBuyButtonMouseMoved(evt);
            }
        });
        unStichedBuyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unStichedBuyButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unStichedBuyButtonMouseExited(evt);
            }
        });
        jPanel2.add(unStichedBuyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 31));

        unStichedBuyButton1.setBackground(new java.awt.Color(176, 233, 225));
        unStichedBuyButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unStichedBuyButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unStichedBuyButton1.setText("Light vehicles");
        unStichedBuyButton1.setOpaque(true);
        unStichedBuyButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unStichedBuyButton1MouseMoved(evt);
            }
        });
        unStichedBuyButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unStichedBuyButton1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unStichedBuyButton1MouseExited(evt);
            }
        });
        jPanel2.add(unStichedBuyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 140, 31));

        unStichedBuyButton2.setBackground(new java.awt.Color(176, 233, 225));
        unStichedBuyButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unStichedBuyButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unStichedBuyButton2.setText("Heavy VehicleParts");
        unStichedBuyButton2.setOpaque(true);
        unStichedBuyButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unStichedBuyButton2MouseMoved(evt);
            }
        });
        unStichedBuyButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unStichedBuyButton2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unStichedBuyButton2MouseExited(evt);
            }
        });
        jPanel2.add(unStichedBuyButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 140, 31));

        unStichedBuyButton3.setBackground(new java.awt.Color(176, 233, 225));
        unStichedBuyButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unStichedBuyButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unStichedBuyButton3.setText("Add Customer");
        unStichedBuyButton3.setOpaque(true);
        unStichedBuyButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unStichedBuyButton3MouseMoved(evt);
            }
        });
        unStichedBuyButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unStichedBuyButton3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unStichedBuyButton3MouseExited(evt);
            }
        });
        jPanel2.add(unStichedBuyButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, 31));

        unStichedBuyButton4.setBackground(new java.awt.Color(176, 233, 225));
        unStichedBuyButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unStichedBuyButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unStichedBuyButton4.setText("Create User");
        unStichedBuyButton4.setOpaque(true);
        unStichedBuyButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unStichedBuyButton4MouseMoved(evt);
            }
        });
        unStichedBuyButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unStichedBuyButton4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unStichedBuyButton4MouseExited(evt);
            }
        });
        jPanel2.add(unStichedBuyButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 31));

        unStichedBuyButton5.setBackground(new java.awt.Color(176, 233, 225));
        unStichedBuyButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unStichedBuyButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unStichedBuyButton5.setText("Profile");
        unStichedBuyButton5.setOpaque(true);
        unStichedBuyButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unStichedBuyButton5MouseMoved(evt);
            }
        });
        unStichedBuyButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unStichedBuyButton5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unStichedBuyButton5MouseExited(evt);
            }
        });
        jPanel2.add(unStichedBuyButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, 31));

        unStichedBuyButton6.setBackground(new java.awt.Color(176, 233, 225));
        unStichedBuyButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unStichedBuyButton6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unStichedBuyButton6.setText("Light Vehicle Parts");
        unStichedBuyButton6.setOpaque(true);
        unStichedBuyButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                unStichedBuyButton6MouseMoved(evt);
            }
        });
        unStichedBuyButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unStichedBuyButton6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unStichedBuyButton6MouseExited(evt);
            }
        });
        jPanel2.add(unStichedBuyButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 140, 31));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 660, 450));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel10.setText("FAW Momentum Motors");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 420, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 660, 130));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        LogOut2.setBackground(new java.awt.Color(255, 255, 255));
        LogOut2.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        LogOut2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut2.setText("Log Out");
        LogOut2.setOpaque(true);
        LogOut2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogOut2MouseMoved(evt);
            }
        });
        LogOut2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(606, Short.MAX_VALUE)
                .addComponent(LogOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogOut2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 670, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOut2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseMoved
        // TODO add your handling code here:
        LogOut2.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_LogOut2MouseMoved

    private void LogOut2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseClicked
        // TODO add your handling code here:
        signOutConfirmation s = new signOutConfirmation(loggedIn);
        dispose();
    }//GEN-LAST:event_LogOut2MouseClicked

    private void LogOut2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseExited
        // TODO add your handling code here:
         LogOut2.setBackground(new java.awt.Color(255,255,255));
        
    }//GEN-LAST:event_LogOut2MouseExited

    private void PretBuyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PretBuyButtonMouseExited
        // TODO add your handling code here:
        PretBuyButton.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_PretBuyButtonMouseExited

    private void PretBuyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PretBuyButtonMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        HeavyVehicles pret=new HeavyVehicles(loggedIn,this);
    }//GEN-LAST:event_PretBuyButtonMouseClicked

    private void PretBuyButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PretBuyButtonMouseMoved
        // TODO add your handling code here:
        PretBuyButton.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_PretBuyButtonMouseMoved

    private void unStichedBuyButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton1MouseMoved
        // TODO add your handling code here:
        unStichedBuyButton1.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_unStichedBuyButton1MouseMoved

    private void unStichedBuyButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LightVehicles l = new LightVehicles(this.loggedIn,this);
    }//GEN-LAST:event_unStichedBuyButton1MouseClicked

    private void unStichedBuyButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton1MouseExited
        // TODO add your handling code here:
         unStichedBuyButton1.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_unStichedBuyButton1MouseExited

    private void unStichedBuyButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton2MouseMoved
        // TODO add your handling code here:
        unStichedBuyButton2.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_unStichedBuyButton2MouseMoved

    private void unStichedBuyButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        HeavyParts p = new HeavyParts(this.loggedIn,this);
    }//GEN-LAST:event_unStichedBuyButton2MouseClicked

    private void unStichedBuyButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton2MouseExited
        // TODO add your handling code here:
        unStichedBuyButton2.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_unStichedBuyButton2MouseExited

    private void unStichedBuyButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton3MouseMoved
        // TODO add your handling code here:
        unStichedBuyButton3.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_unStichedBuyButton3MouseMoved

    private void unStichedBuyButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        UserBookingDetails d = new UserBookingDetails(this.loggedIn,this);
       
    }//GEN-LAST:event_unStichedBuyButton3MouseClicked

    private void unStichedBuyButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton3MouseExited
        // TODO add your handling code here:
        unStichedBuyButton3.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_unStichedBuyButton3MouseExited

    private void unStichedBuyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButtonMouseExited
        // TODO add your handling code here:
        unStichedBuyButton.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_unStichedBuyButtonMouseExited

    private void unStichedBuyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButtonMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        CustomersList c = new CustomersList(this.loggedIn,this);
    }//GEN-LAST:event_unStichedBuyButtonMouseClicked

    private void unStichedBuyButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButtonMouseMoved
        // TODO add your handling code here:
        unStichedBuyButton.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_unStichedBuyButtonMouseMoved

    private void unStichedBuyButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton4MouseMoved
        // TODO add your handling code here:
        unStichedBuyButton4.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_unStichedBuyButton4MouseMoved

    private void unStichedBuyButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        CreateUser s = new CreateUser(this);
        
    }//GEN-LAST:event_unStichedBuyButton4MouseClicked

    private void unStichedBuyButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton4MouseExited
        // TODO add your handling code here:
        unStichedBuyButton4.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_unStichedBuyButton4MouseExited

    private void unStichedBuyButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton5MouseMoved
        // TODO add your handling code here:
         unStichedBuyButton5.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_unStichedBuyButton5MouseMoved

    private void unStichedBuyButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Profile p = new Profile(this.loggedIn,this);
    }//GEN-LAST:event_unStichedBuyButton5MouseClicked

    private void unStichedBuyButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton5MouseExited
        // TODO add your handling code here:
         unStichedBuyButton5.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_unStichedBuyButton5MouseExited

    private void unStichedBuyButton6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton6MouseMoved
        // TODO add your handling code here:
        unStichedBuyButton6.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_unStichedBuyButton6MouseMoved

    private void unStichedBuyButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LightParts p = new LightParts(this.loggedIn,this);
    }//GEN-LAST:event_unStichedBuyButton6MouseClicked

    private void unStichedBuyButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unStichedBuyButton6MouseExited
        // TODO add your handling code here:
        unStichedBuyButton6.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_unStichedBuyButton6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOut2;
    private javax.swing.JLabel PretBuyButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel unStichedBuyButton;
    private javax.swing.JLabel unStichedBuyButton1;
    private javax.swing.JLabel unStichedBuyButton2;
    private javax.swing.JLabel unStichedBuyButton3;
    private javax.swing.JLabel unStichedBuyButton4;
    private javax.swing.JLabel unStichedBuyButton5;
    private javax.swing.JLabel unStichedBuyButton6;
    // End of variables declaration//GEN-END:variables
}
