/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import static java.lang.String.valueOf;
import javax.swing.JFrame;

/**
 *
 * @author imamah
 */
public class Profile extends javax.swing.JFrame {
    String loggedIn;
    JFrame prev;
    /**
     * Creates new form Profile
     */
    public Profile(String email, JFrame j) {
        prev = j;
        this.loggedIn=email;
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        initComponents();
        
        Customer currentCustomer=new Customer();
        currentCustomer=currentCustomer.displayProfile(loggedIn);
        this.Address.setText(currentCustomer.address);
        this.Email1.setText(currentCustomer.email);
         this.Name1.setText(currentCustomer.name);
           this.Password1.setText(currentCustomer.password);
          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        displayName = new javax.swing.JLabel();
        displayAddress = new javax.swing.JLabel();
        displayPassword = new javax.swing.JLabel();
        displayEmail = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        Address = new javax.swing.JTextField();
        Name1 = new javax.swing.JTextField();
        Email1 = new javax.swing.JTextField();
        Password1 = new javax.swing.JTextField();
        refreh = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        LogOut2 = new javax.swing.JLabel();
        Homepage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 47, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 390, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 390, 10));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jPanel7.setBackground(new java.awt.Color(97, 212, 195));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 91, -1, -1));

        jPanel8.setBackground(new java.awt.Color(97, 212, 195));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 169, -1, -1));

        jPanel9.setBackground(new java.awt.Color(97, 212, 195));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 312, -1, -1));

        jPanel10.setBackground(new java.awt.Color(97, 212, 195));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 374, -1, -1));

        jPanel11.setBackground(new java.awt.Color(97, 212, 195));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 436, -1, -1));

        displayName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(displayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        displayAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayAddress.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(displayAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        displayPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayPassword.setForeground(new java.awt.Color(255, 255, 255));
        displayPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayPassword.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(displayPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        displayEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayEmail.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(displayEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 403, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 390, 10));

        Address.setBackground(new java.awt.Color(36, 47, 55));
        Address.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setBorder(null);
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        jPanel2.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 388, 32));

        Name1.setBackground(new java.awt.Color(36, 47, 55));
        Name1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setBorder(null);
        Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name1ActionPerformed(evt);
            }
        });
        jPanel2.add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 388, 32));

        Email1.setEditable(false);
        Email1.setBackground(new java.awt.Color(36, 47, 55));
        Email1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Email1.setForeground(new java.awt.Color(255, 255, 255));
        Email1.setBorder(null);
        Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email1ActionPerformed(evt);
            }
        });
        jPanel2.add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 388, 32));

        Password1.setBackground(new java.awt.Color(36, 47, 55));
        Password1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Password1.setForeground(new java.awt.Color(255, 255, 255));
        Password1.setBorder(null);
        Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1ActionPerformed(evt);
            }
        });
        jPanel2.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 388, 32));

        refreh.setBackground(new java.awt.Color(176, 233, 225));
        refreh.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        refreh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refreh.setText("Refresh");
        refreh.setOpaque(true);
        refreh.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                refrehMouseMoved(evt);
            }
        });
        refreh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refrehMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refrehMouseExited(evt);
            }
        });
        jPanel2.add(refreh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 105, 31));

        Update.setBackground(new java.awt.Color(176, 233, 225));
        Update.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Update.setText("Update");
        Update.setOpaque(true);
        Update.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UpdateMouseMoved(evt);
            }
        });
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        jPanel2.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 105, 31));

        jPanel1.setBackground(new java.awt.Color(176, 233, 225));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("FAW Momentum Motors");

        LogOut2.setBackground(new java.awt.Color(255, 255, 255));
        LogOut2.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        LogOut2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut2.setText("Log Out");
        LogOut2.setOpaque(true);
        LogOut2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogOut2MouseMoved(evt);
            }
        });
        LogOut2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut2MouseExited(evt);
            }
        });

        Homepage.setBackground(new java.awt.Color(255, 255, 255));
        Homepage.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        Homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Homepage.setText("HomePage");
        Homepage.setOpaque(true);
        Homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomepageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(LogOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
       // Editprofile e= new Editprofile();
        
    }//GEN-LAST:event_jPanel7MouseClicked

    private void LogOut2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseMoved
        // TODO add your handling code here:
        LogOut2.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_LogOut2MouseMoved

    private void LogOut2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseClicked
        // TODO add your handling code here:
        signOutConfirmation s = new signOutConfirmation(loggedIn);
        dispose();
    }//GEN-LAST:event_LogOut2MouseClicked

    private void LogOut2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseExited
        // TODO add your handling code here:
        LogOut2.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_LogOut2MouseExited

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name1ActionPerformed

    private void Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email1ActionPerformed

    private void refrehMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refrehMouseMoved
        // TODO add your handling code here:
        refreh.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_refrehMouseMoved

    private void refrehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refrehMouseClicked
        // TODO add your handling code here:
         Customer currentCustomer=new Customer();
        currentCustomer=currentCustomer.displayProfile(loggedIn);
        this.Address.setText(currentCustomer.address);
        this.Email1.setText(currentCustomer.email);
         this.Name1.setText(currentCustomer.name);
           this.Password1.setText(currentCustomer.password);
        
    }//GEN-LAST:event_refrehMouseClicked

    private void refrehMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refrehMouseExited
        // TODO add your handling code here:
        refreh.setBackground(new java.awt.Color(176,233,225));
    }//GEN-LAST:event_refrehMouseExited

    private void UpdateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseMoved
        // TODO add your handling code here:
        Update.setBackground(new java.awt.Color(67,148,136));
    }//GEN-LAST:event_UpdateMouseMoved

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        // TODO add your handling code here:
        Customer c = new Customer();
        c.update(this.Name1.getText(), loggedIn, this.Password1.getText(), this.Address.getText());
        
    }//GEN-LAST:event_UpdateMouseClicked

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        // TODO add your handling code here:
        Update.setBackground(new java.awt.Color(176,233,225));
       
    }//GEN-LAST:event_UpdateMouseExited

    private void Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password1ActionPerformed

    private void HomepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomepageMouseClicked
        // TODO add your handling code here:
        dispose();
        prev.setVisible(true);
    }//GEN-LAST:event_HomepageMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Email1;
    private javax.swing.JLabel Homepage;
    private javax.swing.JLabel LogOut2;
    private javax.swing.JTextField Name1;
    private javax.swing.JTextField Password1;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel displayAddress;
    private javax.swing.JLabel displayEmail;
    private javax.swing.JLabel displayName;
    private javax.swing.JLabel displayPassword;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel refreh;
    // End of variables declaration//GEN-END:variables
}
